title: SF Pizza
tagline: List of pizza places in San Francisco
plugins:
  - jekyll-relative-links
  - jekyll-readme-index
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE
  - README.md
  - TYPES_OF_PIZZA.md.liquid
theme: jekyll-theme-primer
google_analytics: G-Z0K2FPDNK7
