plugins:
  - jekyll-relative-links
  - jekyll-readme-index
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE
  - README.md
theme: jekyll-theme-primer
google_analytics: G-Z0K2FPDNK7
